config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :favorites, only: [:index, :create, :destroy], param: :product_id
  resources :users, only: :show, path: '/user', param: :username
  resources :categories, except: :show
  resources :products, path: '/'
end

app/views/shared/_flash.html.erb
<%= notice %>

<%= alert %>

app/views/shared/_header.html.erb
<div class="bg-white flex justify-between items-center px-2">
    <%= link_to products_path do %>
        <h1 class="text-2xl font-bold text-teal-500"><%= t('app_name') %></h1>
    <% end %>
    <div>
        <%= link_to t('.add'), new_product_path, class: "mx-2 text-teal-500 font-bold" if Current.user %>
        <%= link_to t('.favorites'), favorites_path, class: "mx-2 text-teal-500 font-bold" if Current.user %>
        <%= link_to t('.categories'), categories_path, class: "mx-2 text-teal-500 font-bold" if Current.user&.admin? %>
        <%= link_to t('.login'), new_session_path, class: "mx-2 text-teal-500 font-bold" unless Current.user %>
        <%= link_to t('.register'), new_user_path, class: "mx-2 text-teal-500 font-bold" unless Current.user %>
        <%= link_to t('.logout'), session_path(Current.user.id), data: {
            turbo_method: :delete,
            turbo_confirm: t('common.confirm')
        }, class: "mx-2 text-teal-500 font-bold" if Current.user %>
    </div>
</div>